name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        env:
          REMOTE_PATH: /home/${{ secrets.EC2_USER }}/ais
          BRANCH: main
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          envs: REMOTE_PATH,BRANCH
          script: |
            set -euo pipefail
            cd "$REMOTE_PATH"

            echo "Updating code..."
            git fetch Origin
            git checkout "$BRANCH"
            git reset --hard Origin/"$BRANCH"

            echo "Activating venv..."

            echo "Upgrading pip & installing deps..."
            /home/ec2-user/ais/venv/bin/python -m pip install --upgrade pip
            /home/ec2-user/ais/venv/bin/pip install -r requirements.txt

            echo "Restart backend..."
            sudo systemctl restart ais-backend

            echo "Restart frontend..."
            cd frontend
            npm ci
            npm run build
            sudo systemctl restart ais-frontend

